
spring:
  datasource:
    password: IBib1324656@
    url: jdbc:mysql://localhost:3306/br19testserverdb
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true